### ISSUE TITLE
Video stimuli should be pre-loaded

### ISSUE THREAD

**Issue by jtg567** [mozilla/braingames#11]
The video files used for Shrub should not be loaded ad-hoc trial-by-trial - that adds latency that would/could be awkward for the flow of the experiment.

The jsPsych library has features for preloading images and audio but not yet video. There's [articles I've come across](http://dinbror.dk/blog/how-to-preload-entire-html5-video-before-play-solved/) for doing so, but it is unclear to me how to use those results to provide the jspsych-video plugin with strings as it expects.

**Comment by jtg567** [comment]
After running this on herkoku-stage I can see between 500-2000 ms latencies, depending on the day, to download these videos on the fly. However, upon repeated run-throughs I noticed onced cached the files load more-or-less instantly.

So - I'm hoping if I can just load each of these files once before the experiment they'll be cached and load right away during the study procedure.

**Comment by digitarald** [comment]
If the test setup has a list of URLs for all videos at start, they can be preloaded using xhr and blobs, like the article describes. When the video is already preloaded, further requests to the same URL should be cached already. The other way would be using blobs and giving psych the blog URLs.

**Comment by jodeleeuw** [comment]
If you get video preloading working, I'd welcome a PR to jsPsych to add it as a feature alongside the audio and image preloading!

**Comment by jtg567** [comment]
After #34 landed I ran from -stage to test. It is difficult for me to ascertain its successfulness.

Although the console shows all video file GET requests being fulfilled by XHR prior to the study beginning, there is still a short latency for each file request at trial-time, never greater than 600 ms or so.

So, it seems faster than it was before, but it doesn't seem like the files are completely preloaded:
*the bytes transferred during the preload phase for each video are always less than the total size of the file
*cached files typically load with a note that they were cached in the FF devtools network pane - no such notes present here

**Comment by jtg567** [comment]
Had some team members test this, adding a load screen and calling it good until there's contrary evidence.
