### ISSUE TITLE
Reject mobile users

### ISSUE THREAD

**Issue by jtg567** [mozilla/braingames#18]
Mobile device screens are so much smaller and often viewed in different viewing conditions than other devices. In lieu of that I don't believe results collected from the two should be comparable.

Although some sample vendors we may use to route participants to BrainGames state they screen for mobile devices it may not hurt to check the user agent strings ourselves to ensure/validate.

fwiw I've used https://github.com/selwin/django-user_agents to accomplish that on my personal site, but I'm uncertain whether it is still compatible with the version of Django used for BG. OR - whether it is compatible with jinja templates.

**Comment by jtg567** [comment]
@glogiotatidis would the template filters for the package linked above still work with jinja?

If so, I presume the necessary packages to install would be added to `requirements.txt`?

**Comment by glogiotatidis** [comment]
It will work. You cannot use the filters in jinja but you can directly use `request.user_agent`

```
{% if request.user_agent.is_mobile %}
    Do stuff here...
{% endif %}
```

Yes `requirements.txt` is the place to add packages.

**Comment by jtg567** [comment]
@glogiotatidis I suspect that the packages that django_user_agent parser requires aren't being installed despite following the directions - could you please take a look? https://github.com/mozilla/braingames/pull/33
