### ISSUE TITLE
Make introduction/instruction screens more attractive/explanatory

### ISSUE THREAD

**Issue by jtg567** [mozilla/braingames#19]
Black text on a white background is the default look and doesn't do much to illustrate what we want participants to do.

A designer could do the best job of this quickly, but in lieu of someone dedicated I'll try to put together some kind of walk-through that better describes the task and how to best respond.

**Comment by raymak** [comment]
In terms of looks, I feel the text is too small and too plain. Some highlighting like italics, or bolding could help. I also suggest putting all the instructions in one paragraph.

**Comment by jtg567** [comment]
I made the text bigger and added more formatting without going overboard. Split the instructions over more screens, now navigable with left/right keys (option for mouse buttons showed the buttons but clicking them didn't work).

**Comment by jtg567** [comment]
@raymak how does it look now?

**Comment by raymak** [comment]
Much better!
