### ISSUE TITLE
Answer page issues

### ISSUE THREAD

**Issue by jtg567** [mozilla/braingames#22]
- [x] Browser image/text alignment
- [x] Get better icons for browsers
- [x] Move questions above answers
- [x] Delete periods from answers
- [x] Left to right answers, not top to bottom
- [x] Keypress responses > Mouse responses

**Comment by raymak** [comment]
The second answer could be something around "very similar", "about the same", or "I did not notice a difference". I felt hitting "the same speed" is a big claim to make. On the flip side, people may stop trying to distinguish the clips.

**Comment by jtg567** [comment]
https://github.com/mozilla/braingames/pull/29 solves the first 4 checkboxes above tentatively - please take a look and further critique font size

The 2nd to last issue is a moot point if we switch to keypresses - all key instructions would be added to the prompt image accordingly
