### ISSUE TITLE
People perform best after training/practice

### ISSUE THREAD

**Issue by jtg567** [mozilla/braingames#23]
Either I 

program a separate practice block where participants get the hang of the task until they can hit an accuracy threshold, risking possibly taking a long time and fatiguing themselves for later trials

OR

we ignore the first X number of trials before we (1) consider them for analysis (2) keep track of points for gameified participants

**Comment by raymak** [comment]
I'm for the practice trial. It feels good to know you have not messed up the early trials due to getting surprised by how everything works. When you feel you did badly on the first trials, you lose your momentum for the rest of experiment.

**Comment by jtg567** [comment]
Thinking it over I don't want to do this. I could either do a fixed number of trials that would have variable success with everyone, or train to a threshold of performance to eliminate that potential confound and risk "losing" data from SSI at cost because some/many people will not meet that threshold. Either one eats up time, the latter potentially eats up money at the cost of potentially poorer performance in general.

@MattGrimes - the pilot didn't show any significant "order" effects so I presume people do about as well early in the study as they do later on. If we're concerned about only analyzing the best performance, I advise we do it post hoc by filtering on global accuracy and overall procedure duration. We can exclude people who perform at or below chance and/or outliers who finish too fast or take too long.
