### ISSUE TITLE
The incorrect buzz is really annoying

### ISSUE THREAD

**Issue by raymak** [mozilla/braingames#24]

**Comment by jtg567** [comment]
You're not a Family Feud fan, @raymak ? 😄 

It is obnoxious and could make the task odious to complete if too difficult for someone.

Alternatives to consider:
* make/find a nicer error tone
* make/find complementary ugly/pretty dissonant/consonant error/success tones so we're rewarding to balance out the punishment (still not using something as bad as what I have now)

**Comment by jtg567** [comment]
Replaced with positive and negative feedback tones I made at home with Operator. Forgot to convert from 32-bit 96k WAV to 16-bit 44.1k, did it post-hoc with Audacity.
