### ISSUE TITLE
Have to be able to vary which jsPsych plugins are used for each study

### ISSUE THREAD

**Issue by jtg567** [mozilla/braingames#4]
Not every study utilizes the same jsPsych plugins to achieve the same functionality.

Hosting either incomplete or complete plugins for every study have their obvious drawbacks.

**Comment by jtg567** [comment]
I've already made the code changes for this, now I'm fumbling through the process of submitting as a pull-request from my fork of the repo

**Comment by glogiotatidis** [comment]
You can do it with the current code base by extending the `header` block, e.g in `game.jinja`

```html
{% block header %}
  {{ super() }}
  <script src="{{ static('js/plugins/jspsych-palmer.js') }}"></script>
{% endblock %}
```

I'll update `example-game` to reflect this and btw move the `single-stim` plugin from `basegame` template to `example_game/game.jinja`

**Comment by glogiotatidis** [comment]
Done here https://github.com/mozilla/braingames/commit/2bd6866905f89ca34888288fe2684d3b4c8686b2

**Comment by jtg567** [comment]
That makes sense, I had added a {% block plugins %} to the template but seeing now how this works I understand that'd be redundant. I'd like to handle all of the plugins (`text` as well as `single-stim`) this way and made those changes on branch issue-4 thinking I could land it here but my expectations was unfounded. Separate pull request for that, I guess.
