### ISSUE TITLE
Disqualify participants "live" or post hoc?

### ISSUE THREAD

**Issue by jtg567** [mozilla/braingames#47]
Currently it is possible to filter out people who do things we don't want after we have their data collected.

If SSI requires us to determine who is disqualified on a more ad-hoc basis, a decision has to be made after all of the data is collected.

Right now, everyone who finishes would be sent to the redirect with rst=1, not rst=2 for DQs - if we can't disqualify post hoc we may be throwing data away at cost.

**Comment by MattGrimes** [comment]
I believe they will charge us for anyone that hits the complete redirect. What situations would we dq people after the fact? We could set expectations with them before we begin recruiting and see what they say.

**Comment by jtg567** [comment]
see #43, which was #12 and #21 - I am accustomed to an academic level of control but it could be overkill here.

Right now I'm counting those things as well as I can. We could determine what the thresholds are for those counts via dogfooding (I always got at least one focus loss even if I didn't change programs) and either:

1 - kick people out at the end when we check the counts against our empirical thresholds
2 - kick people out midway through as soon as they meet threshold "bad" event count

**Comment by MattGrimes** [comment]
Kicking people out midway would be easier for dealing with SSI, but that may make it more difficult to get this out the door. We have budget, so it would likely depend on how many people we are kicking out at the end as well.

**Comment by jtg567** [comment]
Fixed/changed some stuff up and this next merge gives us the ability to kick people out midway as soon as they screw up, rather than running the duration of the study.

I say should because I haven't had problems yet but I need everyone else to test for false alarms.
