### ISSUE TITLE
Need to accomodate release and dev versions of jsPsych

### ISSUE THREAD

**Issue by jtg567** [mozilla/braingames#6]
The example-game uses the well documented 5.0.3 release version that's currently in static at a site level.

That version, however, doesn't have the video.js plugin which I need for the study I'm working on, which I simply git clone from their repo.

Would it work to rename the existing `braingames/braingames/jspsych` to `braingames/braingames/jspsych-5.0.3` and reserve `braingames/braingames/jspsych` for the most recent dev edition, which I could update as necessary?

OR would it be better to add jsPsych code as per-study static assets instead?

**Comment by glogiotatidis** [comment]
> Would it work to rename the existing braingames/braingames/jspsych to braingames/braingames/jspsych-5.0.3 and reserve braingames/braingames/jspsych for the most recent dev edition, which I could update as necessary?

> OR would it be better to add jsPsych code as per-study static assets instead?

Renaming that directory will not just work, since this is recognized as an app from django. We can add a jspsych-dev directory and django app and copy code there but if you have different needs per game (library versions, plugins, others) I guess it makes more sense to add needed libraries per game in each game's `static` folder.

**Comment by glogiotatidis** [comment]
I [added an example](https://github.com/mozilla/braingames/tree/master/games/example-game-custom-js) showing how you can use the `static` folder of each game to load jspsych. My understanding is that the library is not necessary backward compatible so I suggest that you always use each game's static folder to store the library and needed plugins for each game. This way each game dire will contain everything needed to work.

Does that work for you @jtg567 ?

**Comment by jtg567** [comment]
Works fine for me, @glogiotatidis. Thank you!

**Comment by glogiotatidis** [comment]
Cool, I'll go ahead and remove the global `jspsych` library then to avoid any confusion.
