### ISSUE TITLE
TemplateDoesNotExist at /game/example-game/

### ISSUE THREAD

**Issue by jtg567** [mozilla/braingames#7]
I'm running locally and get this error when I request http://127.0.0.1:8000/game/example-game/:

Traceback pasted below... 

One odd thing that caught my attention in the braingames.settings DEBUG; the GAMES_DIRECTORY string is being split on the space in my path into two. Probably because I'm on Windows.

```
GAMES_DIRECTORY 	

'C:\\Users\\Josh Gaunt\\Documents\\Projects\\Websites\\braingames\\games

TEMPLATES 	

[{'APP_DIRS': True,
  'BACKEND': 'django_jinja.backend.Jinja2',
  'DIRS': 'C:\\Users\\Josh '
          'Gaunt\\Documents\\Projects\\Websites\\braingames\\games',
  'OPTIONS': {'context_processors': ['session_csrf.context_processor',
                                     'braingames.base.context_processors.settings',
                                     'braingames.base.context_processors.i18n'],
              'match_extension': '.jinja',
              'newstyle_gettext': True}},
 {'APP_DIRS': True,
  'BACKEND': 'django.template.backends.django.DjangoTemplates',
  'OPTIONS': {'context_processors': ['django.contrib.auth.context_processors.auth',
                                     'django.template.context_processors.debug',
                                     'django.template.context_processors.i18n',
                                     'django.template.context_processors.media',
                                     'django.template.context_processors.static',
                                     'django.template.context_processors.tz',
                                     'django.contrib.messages.context_processors.messages',
                                     'session_csrf.context_processor']}}]
```

Environment:

Request Method: GET
Request URL: http://127.0.0.1:8000/game/example-game/

Django Version: 1.10.5
Python Version: 3.6.0
Installed Applications:
['braingames.base',
 'braingames.jspsych',
 'django_jinja',
 'jquery',
 'import_export',
 'django_extensions',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles']
Installed Middleware:
('django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'session_csrf.CsrfMiddleware',
 'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware')

Template loader postmortem
Django tried loading these templates, in this order:

Using engine backend:
    This engine did not provide a list of tried templates.

Using engine django:
    * django.template.loaders.app_directories.Loader: C:\Users\Josh Gaunt\Documents\Projects\Websites\braingames\braingames\base\templates\example-game\game.jinja (Source does not exist)
    * django.template.loaders.app_directories.Loader: C:\Anaconda2\envs\braingames\lib\site-packages\import_export\templates\example-game\game.jinja (Source does not exist)
    * django.template.loaders.app_directories.Loader: C:\Anaconda2\envs\braingames\lib\site-packages\django_extensions\templates\example-game\game.jinja (Source does not exist)
    * django.template.loaders.app_directories.Loader: C:\Anaconda2\envs\braingames\lib\site-packages\django\contrib\admin\templates\example-game\game.jinja (Source does not exist)
    * django.template.loaders.app_directories.Loader: C:\Anaconda2\envs\braingames\lib\site-packages\django\contrib\auth\templates\example-game\game.jinja (Source does not exist)

Traceback:

File "C:\Anaconda2\envs\braingames\lib\site-packages\django\core\handlers\exception.py" in inner
  39.             response = get_response(request)

File "C:\Anaconda2\envs\braingames\lib\site-packages\django\core\handlers\base.py" in _legacy_get_response
  249.             response = self._get_response(request)

File "C:\Anaconda2\envs\braingames\lib\site-packages\django\core\handlers\base.py" in _get_response
  187.                 response = self.process_exception_by_middleware(e, request)

File "C:\Anaconda2\envs\braingames\lib\site-packages\django\core\handlers\base.py" in _get_response
  185.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "C:\Users\Josh Gaunt\Documents\Projects\Websites\braingames\braingames\base\views.py" in game
  21.     return render(request, template, {'gamestatic': partial(utils.gamestatic, game)})

File "C:\Anaconda2\envs\braingames\lib\site-packages\django\shortcuts.py" in render
  30.     content = loader.render_to_string(template_name, context, request, using=using)

File "C:\Anaconda2\envs\braingames\lib\site-packages\django\template\loader.py" in render_to_string
  67.         template = get_template(template_name, using=using)

File "C:\Anaconda2\envs\braingames\lib\site-packages\django\template\loader.py" in get_template
  25.     raise TemplateDoesNotExist(template_name, chain=chain)

Exception Type: TemplateDoesNotExist at /game/example-game/
Exception Value: example-game\game.jinja

**Comment by jtg567** [comment]
I moved my local folder to simplify the path but it still can't find the template(s):
```
TEMPLATES 	

[{'APP_DIRS': True,
  'BACKEND': 'django_jinja.backend.Jinja2',
  'DIRS': ['C:\\GitHub\\braingames\\games'],
```

**Comment by glogiotatidis** [comment]
Can you try again with latest version? Commit https://github.com/mozilla/braingames/commit/a4a5cd4f9c620518073abbe13a4590e9f4f29ab3 could have fixed it.

**Comment by jtg567** [comment]
I can run the example game on heroku stage without issue but still receive the same error running locally.

If you can run locally without issue this could be a Windows thing that may be solved by me running locally with a Docker image? I'm not sure.

I guess I can develop my js files locally outside the repo like I had been and test on stage instead. It adds some steps to my workflow, though, so isn't ideal.

**Comment by glogiotatidis** [comment]
> I guess I can develop my js files locally outside the repo like I had been and test on stage instead. It adds some steps to my workflow, though, so isn't ideal.


Yeah that doesn't sound right, let me take another try.

**Comment by glogiotatidis** [comment]
> If you can run locally without issue this could be a Windows thing that may be solved by me running locally with a Docker image? I'm not sure.

Since I don't run Windows I cannot reproduce the problem and that makes debugging difficult. Instead I just committed https://github.com/mozilla/braingames/commit/0b3373fe5d6a663aec4464503ba29ace773613e9 which adds Docker for development support.

Let me know if that works for you.

**Comment by jtg567** [comment]
It does, thanks.
